version: '3.9'
services:
 # Jellyfin
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /home/user/server/jellyfin/config:/config:Z
      - /home/user/server/jellyfin/cache:/cache:Z
      - /home/user/server/media/movies:/movies:ro
      - /home/user/server/media/books:/books:ro
      - /home/user/server/media/music:/music:ro
      - /home/user/server/media/tv:/tv:ro
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Pacific
    volumes:
      - /home/user/server/prowlarr/config:/config
    restart: unless-stopped

  radarr: # Movies
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/user/server/radarr/config/data:/config
      - /home/user/server/media/movies:/movies
      - /home/user/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr: # TV
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Pacific
    ports:
      - 8989:8989
    volumes:
      - /home/user/server/sonarr/config:/config
      - /home/user/server/media/tv:/tv
      - /home/user/Downloads:/downloads
    restart: unless-stopped

  lidarr:  # Music
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Pacific
    volumes:
      - /home/user/server/lidarr/config:/config
      - /home/user/server/media/music:/music
      - /home/user/Downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  readarr: # Books
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    ports:
      - 8787:8787
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Pacific
    volumes:
      - /home/user/server/readarr/config:/config
      - /home/user/server/media/books:/books
      - /home/user/Downloads:/downloads
    restart: unless-stopped

  bazarr: # Subtitles
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Pacific
    volumes:
      - /home/user/server/bazarr/config:/config
      - /home/user/server/media/movies:/movies
      - /home/user/server/media/tv:/tv
      - /home/user/Downloads:/downloads
    ports:
      - 6767:6767
    restart: unless-stopped

  ######

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Pacific
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/user/server/qbittorrent/config:/config
      - /home/user/Downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

    #to get first admin password
    #docker ps - get container_id
    #docker logs container_id

  dockovpn:
    image: alekslitvinenk/openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194/udp
    environment:
      HOST_ADDR: 10.0.2.15/24
    volumes:
      - ./config:/opt/Dockovpn_data
    restart: always
  # docker compose exec -d dockovpn wget -O /opt/Dockovpn_data/client.ovpn http://127.0.0.1:8080 <- after vpn is up

  # nzbget for easynews
  nzbget:
    image: nzbgetcom/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Pacific
#      - NZBGET_USER=nzbget     #optional
#      - NZBGET_PASS=tegbzn6789 #optional
    volumes:
      - /home/user/server/nzbget/config:/config
      - /home/user/Downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

#Bitwarden Services
  bitwarden:
    depends_on:
      - db
    env_file:
      - settings.env
    image: bitwarden/self-host:beta
    restart: always
    ports:
      - "80:8080"
    volumes:
      - bitwarden:/etc/bitwarden

  db:
    environment:
      MARIADB_USER: "bitwarden"
      MARIADB_PASSWORD: "super_strong_password"
      MARIADB_DATABASE: "bitwarden_vault"
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb:10
    restart: always
    volumes:
      - data:/var/lib/mysql

volumes:
  bitwarden:
  data: